#!/usr/bin/env bash
# Generates ios/Secrets.xcconfig from app/.env.local. Never commit the output.
set -euo pipefail
cd "$(dirname "$0")/.."
ENV_FILE="../app/.env.local"
[ -f "$ENV_FILE" ] || { echo "missing $ENV_FILE" >&2; exit 1; }
url=$(grep '^NEXT_PUBLIC_SUPABASE_URL=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'")
key=$(grep '^NEXT_PUBLIC_SUPABASE_ANON_KEY=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'")
[ -n "$url" ] && [ -n "$key" ] || { echo "missing values in $ENV_FILE" >&2; exit 1; }
# xcconfig treats // as a comment — split the scheme with $()
url_escaped=$(echo "$url" | sed 's|://|:/$()/|')
cat > Secrets.xcconfig << XCCONFIG
// Generated by scripts/gen-secrets.sh — DO NOT COMMIT
SUPABASE_URL = $url_escaped
SUPABASE_ANON_KEY = $key
XCCONFIG
echo "wrote Secrets.xcconfig"
