#!/usr/bin/env bash
# Generates the gitignored xcconfig files that carry Supabase credentials.
#
#   Secrets.Debug.xcconfig   <- app/.env.local        (dev project)
#   Secrets.Release.xcconfig <- app/.env.production   (production project)
#
# Debug builds — Simulator, and anything you run from Xcode — talk to dev.
# Release builds, which is what goes on a phone via TestFlight or a device
# archive, talk to production. That split matters here: the printed QR labels
# point at the live site, so a dev build scanning a real label can land on a
# slug dev has never heard of.
#
# Release is optional. Without app/.env.production this writes the Debug file
# and warns, so Simulator work keeps going; a Release build will then fail
# loudly at launch rather than silently using dev credentials.
set -euo pipefail
cd "$(dirname "$0")/.."

# xcconfig treats // as the start of a comment, so the URL scheme's slashes
# have to be split with an empty $() expansion.
write_config() {
  local env_file="$1" out_file="$2" label="$3"
  local url key
  url=$(grep '^NEXT_PUBLIC_SUPABASE_URL=' "$env_file" | cut -d= -f2- | tr -d '"' | tr -d "'")
  key=$(grep '^NEXT_PUBLIC_SUPABASE_ANON_KEY=' "$env_file" | cut -d= -f2- | tr -d '"' | tr -d "'")
  if [ -z "$url" ] || [ -z "$key" ]; then
    echo "error: $env_file is missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY" >&2
    exit 1
  fi
  cat > "$out_file" << XCCONFIG
// Generated by scripts/gen-secrets.sh from $env_file — DO NOT COMMIT
// $label
SUPABASE_URL = $(echo "$url" | sed 's|://|:/$()/|')
SUPABASE_ANON_KEY = $key
XCCONFIG
  echo "wrote $out_file ($label)"
}

DEV_ENV="../app/.env.local"
PROD_ENV="../app/.env.production"

[ -f "$DEV_ENV" ] || { echo "error: missing $DEV_ENV" >&2; exit 1; }
write_config "$DEV_ENV" "Secrets.Debug.xcconfig" "development"

if [ -f "$PROD_ENV" ]; then
  write_config "$PROD_ENV" "Secrets.Release.xcconfig" "production"
else
  # Placeholder so Release still configures; SupabaseManager fails fast with a
  # clear message rather than quietly falling back to the dev project.
  cat > Secrets.Release.xcconfig << 'XCCONFIG'
// Generated by scripts/gen-secrets.sh — DO NOT COMMIT
// No app/.env.production found. Add it and re-run this script before
// building for a device; launching a Release build like this fails on
// purpose rather than silently using development credentials.
SUPABASE_URL =
SUPABASE_ANON_KEY =
XCCONFIG
  echo "warning: no $PROD_ENV — wrote an empty Secrets.Release.xcconfig." >&2
  echo "         Simulator (Debug) builds work; device (Release) builds will not." >&2
fi
