import Foundation
import Supabase

/// Owns the single Supabase client used throughout the app.
///
/// Reads the project URL and anon key out of Info.plist, which xcodegen
/// populates at build time from `Secrets.Debug.xcconfig` (dev) or
/// `Secrets.Release.xcconfig` (production), both generated by
/// `scripts/gen-secrets.sh` and both gitignored.
///
/// Empty values are treated as missing on purpose. A Release build with no
/// `app/.env.production` gets an empty config, and crashing here is the point
/// — far better than a device build silently talking to the dev project.
final class SupabaseManager: @unchecked Sendable {
    static let shared = SupabaseManager()

    let client: SupabaseClient

    private init() {
        guard let urlString = Bundle.main.object(forInfoDictionaryKey: "SupabaseURL") as? String,
              let url = URL(string: urlString),
              !urlString.isEmpty
        else {
            fatalError(Self.missingCredentialsMessage(for: "SupabaseURL"))
        }

        guard let anonKey = Bundle.main.object(forInfoDictionaryKey: "SupabaseAnonKey") as? String,
              !anonKey.isEmpty
        else {
            fatalError(Self.missingCredentialsMessage(for: "SupabaseAnonKey"))
        }

        client = SupabaseClient(supabaseURL: url, supabaseKey: anonKey)
    }

    private static func missingCredentialsMessage(for key: String) -> String {
        """
        Missing or empty \(key) in Info.plist.
        Run ios/scripts/gen-secrets.sh. A Release build also needs \
        app/.env.production to exist — without it the release config is \
        written empty on purpose, so a device build cannot quietly fall \
        back to the development project.
        """
    }
}
