// This file is auto-generated by: supabase gen types typescript --project-id <ref> > src/lib/types/database.types.ts
// Re-run after every migration.
//
// Until the Supabase project is created and migrations are applied,
// this is a placeholder. The Database type below will be replaced by the
// generated output.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
